fixed delink

diff --git a/bin/delink b/bin/delink
--- a/bin/delink
+++ b/bin/delink
@@ -1,9 +1,11 @@
 #!/bin/bash
 
 # converts symbolic link into a regular file
-echo "$1"
-[ ! -L "$1" ] && echo "ABORT: $1 is not a link"; exit 1;
-[   -L "$1" ] && echo "link is real"
+#[   -L "$1" ] && cp --remove-destination "$(readlink "$1")" "$1" 
 
-
-#[ -L "$1" ] && cp -v --remove-destination "$(readlink "$1")" "$1"
+[ !  -L "$1" ] && echo "ABORT: $1 is not a link" && exit 1;
+if [ -L "$1" ]; then
+    P=$(readlink "$1")
+    rm "$1"
+    cp "$P" .
+fi
